/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgentSystemAdbAuth model module.
 * @module model/AgentSystemAdbAuth
 * @version 0.4.0
 */
class AgentSystemAdbAuth {
    /**
     * Constructs a new <code>AgentSystemAdbAuth</code>.
     * 
     * @alias module:model/AgentSystemAdbAuth
     */
    constructor() { 
        
        AgentSystemAdbAuth.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgentSystemAdbAuth</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgentSystemAdbAuth} obj Optional instance to populate.
     * @return {module:model/AgentSystemAdbAuth} The populated <code>AgentSystemAdbAuth</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgentSystemAdbAuth();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgentSystemAdbAuth</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgentSystemAdbAuth</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * 
 * @member {Boolean} enabled
 */
AgentSystemAdbAuth.prototype['enabled'] = undefined;






export default AgentSystemAdbAuth;

