/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 4.2.0-6a4b86f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BtraceEnableOptions model module.
 * @module model/BtraceEnableOptions
 * @version 0.2.0
 */
class BtraceEnableOptions {
    /**
     * Constructs a new <code>BtraceEnableOptions</code>.
     * 
     * @alias module:model/BtraceEnableOptions
     */
    constructor() { 
        
        BtraceEnableOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BtraceEnableOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BtraceEnableOptions} obj Optional instance to populate.
     * @return {module:model/BtraceEnableOptions} The populated <code>BtraceEnableOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BtraceEnableOptions();

            if (data.hasOwnProperty('ranges')) {
                obj['ranges'] = ApiClient.convertToType(data['ranges'], [['String']]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BtraceEnableOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BtraceEnableOptions</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['ranges'])) {
            throw new Error("Expected the field `ranges` to be an array in the JSON data but got " + data['ranges']);
        }

        return true;
    }


}



/**
 * 
 * @member {Array.<Array.<String>>} ranges
 */
BtraceEnableOptions.prototype['ranges'] = undefined;






export default BtraceEnableOptions;

