/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoordinatorConfig from './CoordinatorConfig';

/**
 * The ClusterConfigurationPayload model module.
 * @module model/ClusterConfigurationPayload
 * @version 0.4.3
 */
class ClusterConfigurationPayload {
    /**
     * Constructs a new <code>ClusterConfigurationPayload</code>.
     * 
     * @alias module:model/ClusterConfigurationPayload
     */
    constructor() { 
        
        ClusterConfigurationPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClusterConfigurationPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClusterConfigurationPayload} obj Optional instance to populate.
     * @return {module:model/ClusterConfigurationPayload} The populated <code>ClusterConfigurationPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterConfigurationPayload();

            if (data.hasOwnProperty('snapshotLimit')) {
                obj['snapshotLimit'] = ApiClient.convertToType(data['snapshotLimit'], 'Number');
            }
            if (data.hasOwnProperty('coordinatorConfig')) {
                obj['coordinatorConfig'] = CoordinatorConfig.constructFromObject(data['coordinatorConfig']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClusterConfigurationPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ClusterConfigurationPayload</code>.
     */
    static validateJSON(data) {
        // validate the optional field `coordinatorConfig`
        if (data['coordinatorConfig']) { // data not null
          CoordinatorConfig.validateJSON(data['coordinatorConfig']);
        }

        return true;
    }


}



/**
 * Designates the maximum number of snapshots that can be taken in a cluster
 * @member {Number} snapshotLimit
 */
ClusterConfigurationPayload.prototype['snapshotLimit'] = undefined;

/**
 * @member {module:model/CoordinatorConfig} coordinatorConfig
 */
ClusterConfigurationPayload.prototype['coordinatorConfig'] = undefined;






export default ClusterConfigurationPayload;

