/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExtendedFirmwareAssetInfo model module.
 * @module model/ExtendedFirmwareAssetInfo
 * @version 0.4.3
 */
class ExtendedFirmwareAssetInfo {
    /**
     * Constructs a new <code>ExtendedFirmwareAssetInfo</code>.
     * 
     * @alias module:model/ExtendedFirmwareAssetInfo
     * @param firmwares {Array.<String>} Firmware Records from FW Service
     * @param instances {Array.<String>} Instances using one of the firmwares, and thus the asset
     */
    constructor(firmwares, instances) { 
        
        ExtendedFirmwareAssetInfo.initialize(this, firmwares, instances);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firmwares, instances) { 
        obj['firmwares'] = firmwares;
        obj['instances'] = instances;
    }

    /**
     * Constructs a <code>ExtendedFirmwareAssetInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExtendedFirmwareAssetInfo} obj Optional instance to populate.
     * @return {module:model/ExtendedFirmwareAssetInfo} The populated <code>ExtendedFirmwareAssetInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtendedFirmwareAssetInfo();

            if (data.hasOwnProperty('firmwares')) {
                obj['firmwares'] = ApiClient.convertToType(data['firmwares'], ['String']);
            }
            if (data.hasOwnProperty('instances')) {
                obj['instances'] = ApiClient.convertToType(data['instances'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExtendedFirmwareAssetInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExtendedFirmwareAssetInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExtendedFirmwareAssetInfo.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['firmwares'])) {
            throw new Error("Expected the field `firmwares` to be an array in the JSON data but got " + data['firmwares']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['instances'])) {
            throw new Error("Expected the field `instances` to be an array in the JSON data but got " + data['instances']);
        }

        return true;
    }


}

ExtendedFirmwareAssetInfo.RequiredProperties = ["firmwares", "instances"];

/**
 * Firmware Records from FW Service
 * @member {Array.<String>} firmwares
 */
ExtendedFirmwareAssetInfo.prototype['firmwares'] = undefined;

/**
 * Instances using one of the firmwares, and thus the asset
 * @member {Array.<String>} instances
 */
ExtendedFirmwareAssetInfo.prototype['instances'] = undefined;






export default ExtendedFirmwareAssetInfo;

