/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FirmwareAsset model module.
 * @module model/FirmwareAsset
 * @version 0.4.3
 */
class FirmwareAsset {
    /**
     * Constructs a new <code>FirmwareAsset</code>.
     * 
     * @alias module:model/FirmwareAsset
     * @param domain {String} 
     * @param url {String} 
     * @param payload {String} 
     * @param size {Number} 
     */
    constructor(domain, url, payload, size) { 
        
        FirmwareAsset.initialize(this, domain, url, payload, size);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, domain, url, payload, size) { 
        obj['domain'] = domain;
        obj['url'] = url;
        obj['payload'] = payload;
        obj['size'] = size;
    }

    /**
     * Constructs a <code>FirmwareAsset</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FirmwareAsset} obj Optional instance to populate.
     * @return {module:model/FirmwareAsset} The populated <code>FirmwareAsset</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FirmwareAsset();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('md5sum')) {
                obj['md5sum'] = ApiClient.convertToType(data['md5sum'], 'String');
            }
            if (data.hasOwnProperty('sha1sum')) {
                obj['sha1sum'] = ApiClient.convertToType(data['sha1sum'], 'String');
            }
            if (data.hasOwnProperty('sha256sum')) {
                obj['sha256sum'] = ApiClient.convertToType(data['sha256sum'], 'String');
            }
            if (data.hasOwnProperty('uploaddate')) {
                obj['uploaddate'] = ApiClient.convertToType(data['uploaddate'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FirmwareAsset</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FirmwareAsset</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FirmwareAsset.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['payload'] && !(typeof data['payload'] === 'string' || data['payload'] instanceof String)) {
            throw new Error("Expected the field `payload` to be a primitive type in the JSON string but got " + data['payload']);
        }
        // ensure the json data is a string
        if (data['md5sum'] && !(typeof data['md5sum'] === 'string' || data['md5sum'] instanceof String)) {
            throw new Error("Expected the field `md5sum` to be a primitive type in the JSON string but got " + data['md5sum']);
        }
        // ensure the json data is a string
        if (data['sha1sum'] && !(typeof data['sha1sum'] === 'string' || data['sha1sum'] instanceof String)) {
            throw new Error("Expected the field `sha1sum` to be a primitive type in the JSON string but got " + data['sha1sum']);
        }
        // ensure the json data is a string
        if (data['sha256sum'] && !(typeof data['sha256sum'] === 'string' || data['sha256sum'] instanceof String)) {
            throw new Error("Expected the field `sha256sum` to be a primitive type in the JSON string but got " + data['sha256sum']);
        }
        // ensure the json data is a string
        if (data['uploaddate'] && !(typeof data['uploaddate'] === 'string' || data['uploaddate'] instanceof String)) {
            throw new Error("Expected the field `uploaddate` to be a primitive type in the JSON string but got " + data['uploaddate']);
        }
        // ensure the json data is a string
        if (data['createdAt'] && !(typeof data['createdAt'] === 'string' || data['createdAt'] instanceof String)) {
            throw new Error("Expected the field `createdAt` to be a primitive type in the JSON string but got " + data['createdAt']);
        }
        // ensure the json data is a string
        if (data['updatedAt'] && !(typeof data['updatedAt'] === 'string' || data['updatedAt'] instanceof String)) {
            throw new Error("Expected the field `updatedAt` to be a primitive type in the JSON string but got " + data['updatedAt']);
        }

        return true;
    }


}

FirmwareAsset.RequiredProperties = ["domain", "url", "payload", "size"];

/**
 * 
 * @member {String} domain
 */
FirmwareAsset.prototype['domain'] = undefined;

/**
 * 
 * @member {String} url
 */
FirmwareAsset.prototype['url'] = undefined;

/**
 * 
 * @member {String} payload
 */
FirmwareAsset.prototype['payload'] = undefined;

/**
 * 
 * @member {Number} size
 */
FirmwareAsset.prototype['size'] = undefined;

/**
 * 
 * @member {String} md5sum
 */
FirmwareAsset.prototype['md5sum'] = undefined;

/**
 * 
 * @member {String} sha1sum
 */
FirmwareAsset.prototype['sha1sum'] = undefined;

/**
 * 
 * @member {String} sha256sum
 */
FirmwareAsset.prototype['sha256sum'] = undefined;

/**
 * 
 * @member {String} uploaddate
 */
FirmwareAsset.prototype['uploaddate'] = undefined;

/**
 * 
 * @member {String} createdAt
 */
FirmwareAsset.prototype['createdAt'] = undefined;

/**
 * 
 * @member {String} updatedAt
 */
FirmwareAsset.prototype['updatedAt'] = undefined;






export default FirmwareAsset;

