/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 5.2.0-17368
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Bit from './Bit';

/**
 * The GpioStateDefinition model module.
 * @module model/GpioStateDefinition
 * @version 0.3.3
 */
class GpioStateDefinition {
    /**
     * Constructs a new <code>GpioStateDefinition</code>.
     * 
     * @alias module:model/GpioStateDefinition
     * @param bitCount {Number} count of bits in members of this bank
     * @param banks {Array.<Array.<module:model/Bit>>} bits for each bank of this name as an array of arrays
     */
    constructor(bitCount, banks) { 
        
        GpioStateDefinition.initialize(this, bitCount, banks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bitCount, banks) { 
        obj['bitCount'] = bitCount;
        obj['banks'] = banks;
    }

    /**
     * Constructs a <code>GpioStateDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GpioStateDefinition} obj Optional instance to populate.
     * @return {module:model/GpioStateDefinition} The populated <code>GpioStateDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GpioStateDefinition();

            if (data.hasOwnProperty('bitCount')) {
                obj['bitCount'] = ApiClient.convertToType(data['bitCount'], 'Number');
            }
            if (data.hasOwnProperty('banks')) {
                obj['banks'] = ApiClient.convertToType(data['banks'], [[Bit]]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GpioStateDefinition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GpioStateDefinition</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GpioStateDefinition.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['banks'])) {
            throw new Error("Expected the field `banks` to be an array in the JSON data but got " + data['banks']);
        }

        return true;
    }


}

GpioStateDefinition.RequiredProperties = ["bitCount", "banks"];

/**
 * count of bits in members of this bank
 * @member {Number} bitCount
 */
GpioStateDefinition.prototype['bitCount'] = undefined;

/**
 * bits for each bank of this name as an array of arrays
 * @member {Array.<Array.<module:model/Bit>>} banks
 */
GpioStateDefinition.prototype['banks'] = undefined;






export default GpioStateDefinition;

