/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InputResponse model module.
 * @module model/InputResponse
 * @version 0.4.1
 */
class InputResponse {
    /**
     * Constructs a new <code>InputResponse</code>.
     * 
     * @alias module:model/InputResponse
     */
    constructor() { 
        
        InputResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InputResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InputResponse} obj Optional instance to populate.
     * @return {module:model/InputResponse} The populated <code>InputResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InputResponse();

            if (data.hasOwnProperty('eta')) {
                obj['eta'] = ApiClient.convertToType(data['eta'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InputResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InputResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Expected time to complete
 * @member {Number} eta
 */
InputResponse.prototype['eta'] = undefined;






export default InputResponse;

