/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstanceBootOptionsKernel model module.
 * @module model/InstanceBootOptionsKernel
 * @version 0.4.3
 */
class InstanceBootOptionsKernel {
    /**
     * Constructs a new <code>InstanceBootOptionsKernel</code>.
     * 
     * @alias module:model/InstanceBootOptionsKernel
     */
    constructor() { 
        
        InstanceBootOptionsKernel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstanceBootOptionsKernel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceBootOptionsKernel} obj Optional instance to populate.
     * @return {module:model/InstanceBootOptionsKernel} The populated <code>InstanceBootOptionsKernel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceBootOptionsKernel();

            if (data.hasOwnProperty('firmwarePath')) {
                obj['firmwarePath'] = ApiClient.convertToType(data['firmwarePath'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstanceBootOptionsKernel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstanceBootOptionsKernel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['firmwarePath'] && !(typeof data['firmwarePath'] === 'string' || data['firmwarePath'] instanceof String)) {
            throw new Error("Expected the field `firmwarePath` to be a primitive type in the JSON string but got " + data['firmwarePath']);
        }

        return true;
    }


}



/**
 * The relative path within the firmware to the kernel file that has been bundled up with the selected firmware
 * @member {String} firmwarePath
 */
InstanceBootOptionsKernel.prototype['firmwarePath'] = undefined;






export default InstanceBootOptionsKernel;

