/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 4.2.0-6a4b86f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstanceStopOptions model module.
 * @module model/InstanceStopOptions
 * @version 0.2.0
 */
class InstanceStopOptions {
    /**
     * Constructs a new <code>InstanceStopOptions</code>.
     * 
     * @alias module:model/InstanceStopOptions
     */
    constructor() { 
        
        InstanceStopOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstanceStopOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceStopOptions} obj Optional instance to populate.
     * @return {module:model/InstanceStopOptions} The populated <code>InstanceStopOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceStopOptions();

            if (data.hasOwnProperty('soft')) {
                obj['soft'] = ApiClient.convertToType(data['soft'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstanceStopOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstanceStopOptions</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Request VM OS power down
 * @member {Boolean} soft
 */
InstanceStopOptions.prototype['soft'] = undefined;






export default InstanceStopOptions;

