/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstallFirmwareResponse model module.
 * @module model/InstallFirmwareResponse
 * @version 0.4.3
 */
class InstallFirmwareResponse {
    /**
     * Constructs a new <code>InstallFirmwareResponse</code>.
     * 
     * @alias module:model/InstallFirmwareResponse
     */
    constructor() { 
        
        InstallFirmwareResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstallFirmwareResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstallFirmwareResponse} obj Optional instance to populate.
     * @return {module:model/InstallFirmwareResponse} The populated <code>InstallFirmwareResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstallFirmwareResponse();

            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('installedFirmwareUrl')) {
                obj['installedFirmwareUrl'] = ApiClient.convertToType(data['installedFirmwareUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstallFirmwareResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstallFirmwareResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['taskId'] && !(typeof data['taskId'] === 'string' || data['taskId'] instanceof String)) {
            throw new Error("Expected the field `taskId` to be a primitive type in the JSON string but got " + data['taskId']);
        }
        // ensure the json data is a string
        if (data['installedFirmwareUrl'] && !(typeof data['installedFirmwareUrl'] === 'string' || data['installedFirmwareUrl'] instanceof String)) {
            throw new Error("Expected the field `installedFirmwareUrl` to be a primitive type in the JSON string but got " + data['installedFirmwareUrl']);
        }

        return true;
    }


}



/**
 * Task ID
 * @member {String} taskId
 */
InstallFirmwareResponse.prototype['taskId'] = undefined;

/**
 * Installed Firmware URL
 * @member {String} installedFirmwareUrl
 */
InstallFirmwareResponse.prototype['installedFirmwareUrl'] = undefined;






export default InstallFirmwareResponse;

