/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstanceInterface from './InstanceInterface';

/**
 * The InterconnectResponse model module.
 * @module model/InterconnectResponse
 * @version 0.4.3
 */
class InterconnectResponse {
    /**
     * Constructs a new <code>InterconnectResponse</code>.
     * 
     * @alias module:model/InterconnectResponse
     */
    constructor() { 
        
        InterconnectResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InterconnectResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InterconnectResponse} obj Optional instance to populate.
     * @return {module:model/InterconnectResponse} The populated <code>InterconnectResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InterconnectResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('interfaces')) {
                obj['interfaces'] = ApiClient.convertToType(data['interfaces'], [InstanceInterface]);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InterconnectResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InterconnectResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['protocol'] && !(typeof data['protocol'] === 'string' || data['protocol'] instanceof String)) {
            throw new Error("Expected the field `protocol` to be a primitive type in the JSON string but got " + data['protocol']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['project'] && !(typeof data['project'] === 'string' || data['project'] instanceof String)) {
            throw new Error("Expected the field `project` to be a primitive type in the JSON string but got " + data['project']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        if (data['interfaces']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['interfaces'])) {
                throw new Error("Expected the field `interfaces` to be an array in the JSON data but got " + data['interfaces']);
            }
            // validate the optional field `interfaces` (array)
            for (const item of data['interfaces']) {
                InstanceInterface.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['createdAt'] && !(typeof data['createdAt'] === 'string' || data['createdAt'] instanceof String)) {
            throw new Error("Expected the field `createdAt` to be a primitive type in the JSON string but got " + data['createdAt']);
        }
        // ensure the json data is a string
        if (data['updatedAt'] && !(typeof data['updatedAt'] === 'string' || data['updatedAt'] instanceof String)) {
            throw new Error("Expected the field `updatedAt` to be a primitive type in the JSON string but got " + data['updatedAt']);
        }

        return true;
    }


}



/**
 * The interconnect identifier
 * @member {String} id
 */
InterconnectResponse.prototype['id'] = undefined;

/**
 * The name of the interconnect
 * @member {String} name
 */
InterconnectResponse.prototype['name'] = undefined;

/**
 * The protocol used by the interconnect
 * @member {String} protocol
 */
InterconnectResponse.prototype['protocol'] = undefined;

/**
 * The type of interconnect
 * @member {module:model/InterconnectResponse.TypeEnum} type
 */
InterconnectResponse.prototype['type'] = undefined;

/**
 * The UUID of the project
 * @member {String} project
 */
InterconnectResponse.prototype['project'] = undefined;

/**
 * The current status of the interconnect
 * @member {String} status
 */
InterconnectResponse.prototype['status'] = undefined;

/**
 * Array of instance interfaces
 * @member {Array.<module:model/InstanceInterface>} interfaces
 */
InterconnectResponse.prototype['interfaces'] = undefined;

/**
 * Creation timestamp
 * @member {String} createdAt
 */
InterconnectResponse.prototype['createdAt'] = undefined;

/**
 * Last update timestamp
 * @member {String} updatedAt
 */
InterconnectResponse.prototype['updatedAt'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
InterconnectResponse['TypeEnum'] = {

    /**
     * value: "hub"
     * @const
     */
    "hub": "hub",

    /**
     * value: "switch"
     * @const
     */
    "switch": "switch"
};



export default InterconnectResponse;

