/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InviteRevokeParamsIds from './InviteRevokeParamsIds';

/**
 * The InviteRevokeParams model module.
 * @module model/InviteRevokeParams
 * @version 0.4.1
 */
class InviteRevokeParams {
    /**
     * Constructs a new <code>InviteRevokeParams</code>.
     * 
     * @alias module:model/InviteRevokeParams
     */
    constructor() { 
        
        InviteRevokeParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InviteRevokeParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InviteRevokeParams} obj Optional instance to populate.
     * @return {module:model/InviteRevokeParams} The populated <code>InviteRevokeParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteRevokeParams();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = InviteRevokeParamsIds.constructFromObject(data['ids']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteRevokeParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteRevokeParams</code>.
     */
    static validateJSON(data) {
        // validate the optional field `ids`
        if (data['ids']) { // data not null
          InviteRevokeParamsIds.validateJSON(data['ids']);
        }

        return true;
    }


}



/**
 * @member {module:model/InviteRevokeParamsIds} ids
 */
InviteRevokeParams.prototype['ids'] = undefined;






export default InviteRevokeParams;

