/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Maintenance model module.
 * @module model/Maintenance
 * @version 0.4.0
 */
class Maintenance {
    /**
     * Constructs a new <code>Maintenance</code>.
     * 
     * @alias module:model/Maintenance
     */
    constructor() { 
        
        Maintenance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Maintenance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Maintenance} obj Optional instance to populate.
     * @return {module:model/Maintenance} The populated <code>Maintenance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Maintenance();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = ApiClient.convertToType(data['header'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Maintenance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Maintenance</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['header'] && !(typeof data['header'] === 'string' || data['header'] instanceof String)) {
            throw new Error("Expected the field `header` to be a primitive type in the JSON string but got " + data['header']);
        }

        return true;
    }


}



/**
 * Maintenance message
 * @member {String} message
 */
Maintenance.prototype['message'] = undefined;

/**
 * Maintenance header
 * @member {String} header
 */
Maintenance.prototype['header'] = undefined;






export default Maintenance;

