/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworkConnection from './NetworkConnection';

/**
 * The NetworkConnectionOffsetPaginationResult model module.
 * @module model/NetworkConnectionOffsetPaginationResult
 * @version 0.4.1
 */
class NetworkConnectionOffsetPaginationResult {
    /**
     * Constructs a new <code>NetworkConnectionOffsetPaginationResult</code>.
     * Network Connection Offset Pagination Result
     * @alias module:model/NetworkConnectionOffsetPaginationResult
     * @param total {Number} Total number of items.
     * @param count {Number} The number of items returned in this result.
     * @param limit {Number} The maximum number of items that could be returned for this result.
     * @param offset {Number} That starting item 0-indexed.
     * @param results {Array.<module:model/NetworkConnection>} Array of network connections associated with this domain.
     */
    constructor(total, count, limit, offset, results) { 
        
        NetworkConnectionOffsetPaginationResult.initialize(this, total, count, limit, offset, results);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, count, limit, offset, results) { 
        obj['total'] = total;
        obj['count'] = count;
        obj['limit'] = limit;
        obj['offset'] = offset;
        obj['results'] = results;
    }

    /**
     * Constructs a <code>NetworkConnectionOffsetPaginationResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkConnectionOffsetPaginationResult} obj Optional instance to populate.
     * @return {module:model/NetworkConnectionOffsetPaginationResult} The populated <code>NetworkConnectionOffsetPaginationResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkConnectionOffsetPaginationResult();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [NetworkConnection]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NetworkConnectionOffsetPaginationResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NetworkConnectionOffsetPaginationResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NetworkConnectionOffsetPaginationResult.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                NetworkConnection.validateJSON(item);
            };
        }

        return true;
    }


}

NetworkConnectionOffsetPaginationResult.RequiredProperties = ["total", "count", "limit", "offset", "results"];

/**
 * Total number of items.
 * @member {Number} total
 */
NetworkConnectionOffsetPaginationResult.prototype['total'] = undefined;

/**
 * The number of items returned in this result.
 * @member {Number} count
 */
NetworkConnectionOffsetPaginationResult.prototype['count'] = undefined;

/**
 * The maximum number of items that could be returned for this result.
 * @member {Number} limit
 */
NetworkConnectionOffsetPaginationResult.prototype['limit'] = undefined;

/**
 * That starting item 0-indexed.
 * @member {Number} offset
 */
NetworkConnectionOffsetPaginationResult.prototype['offset'] = undefined;

/**
 * Array of network connections associated with this domain.
 * @member {Array.<module:model/NetworkConnection>} results
 */
NetworkConnectionOffsetPaginationResult.prototype['results'] = undefined;






export default NetworkConnectionOffsetPaginationResult;

