/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NodeInformation from './NodeInformation';

/**
 * The NodeUpdatesFailed model module.
 * @module model/NodeUpdatesFailed
 * @version 0.4.3
 */
class NodeUpdatesFailed {
    /**
     * Constructs a new <code>NodeUpdatesFailed</code>.
     * 
     * @alias module:model/NodeUpdatesFailed
     */
    constructor() { 
        
        NodeUpdatesFailed.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NodeUpdatesFailed</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NodeUpdatesFailed} obj Optional instance to populate.
     * @return {module:model/NodeUpdatesFailed} The populated <code>NodeUpdatesFailed</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeUpdatesFailed();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], [NodeInformation]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NodeUpdatesFailed</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NodeUpdatesFailed</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['nodes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['nodes'])) {
                throw new Error("Expected the field `nodes` to be an array in the JSON data but got " + data['nodes']);
            }
            // validate the optional field `nodes` (array)
            for (const item of data['nodes']) {
                NodeInformation.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Instructions to try again or resolve manually
 * @member {String} message
 */
NodeUpdatesFailed.prototype['message'] = undefined;

/**
 * List of nodes that failed to receive updates.
 * @member {Array.<module:model/NodeInformation>} nodes
 */
NodeUpdatesFailed.prototype['nodes'] = undefined;






export default NodeUpdatesFailed;

