/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchInstanceReadOnly model module.
 * @module model/PatchInstanceReadOnly
 * @version 0.4.3
 */
class PatchInstanceReadOnly {
    /**
     * Constructs a new <code>PatchInstanceReadOnly</code>.
     * 
     * @alias module:model/PatchInstanceReadOnly
     */
    constructor() { 
        
        PatchInstanceReadOnly.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchInstanceReadOnly</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchInstanceReadOnly} obj Optional instance to populate.
     * @return {module:model/PatchInstanceReadOnly} The populated <code>PatchInstanceReadOnly</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchInstanceReadOnly();

            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchInstanceReadOnly</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchInstanceReadOnly</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['readOnly'] && !(typeof data['readOnly'] === 'string' || data['readOnly'] instanceof String)) {
            throw new Error("Expected the field `readOnly` to be a primitive type in the JSON string but got " + data['readOnly']);
        }

        return true;
    }


}



/**
 * The desired state of readOnly. Possible values: 'enabled', 'disabled'.
 * @member {String} readOnly
 */
PatchInstanceReadOnly.prototype['readOnly'] = undefined;






export default PatchInstanceReadOnly;

