/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectNetworkState model module.
 * @module model/ProjectNetworkState
 * @version 0.4.1
 */
class ProjectNetworkState {
    /**
     * Constructs a new <code>ProjectNetworkState</code>.
     * ProjectNetworkState
     * @alias module:model/ProjectNetworkState
     * @param state {String} State of the project network connection. One of: disconnected, disconnecting, connecting, connected, error
     */
    constructor(state) { 
        
        ProjectNetworkState.initialize(this, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state) { 
        obj['state'] = state;
    }

    /**
     * Constructs a <code>ProjectNetworkState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectNetworkState} obj Optional instance to populate.
     * @return {module:model/ProjectNetworkState} The populated <code>ProjectNetworkState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectNetworkState();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProjectNetworkState</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProjectNetworkState</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProjectNetworkState.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }

        return true;
    }


}

ProjectNetworkState.RequiredProperties = ["state"];

/**
 * State of the project network connection. One of: disconnected, disconnecting, connecting, connected, error
 * @member {String} state
 */
ProjectNetworkState.prototype['state'] = undefined;

/**
 * Additional parameters for the network state.
 * @member {Object} details
 */
ProjectNetworkState.prototype['details'] = undefined;






export default ProjectNetworkState;

