/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResetLinkInfoReturn model module.
 * @module model/ResetLinkInfoReturn
 * @version 0.4.3
 */
class ResetLinkInfoReturn {
    /**
     * Constructs a new <code>ResetLinkInfoReturn</code>.
     * 
     * @alias module:model/ResetLinkInfoReturn
     */
    constructor() { 
        
        ResetLinkInfoReturn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResetLinkInfoReturn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResetLinkInfoReturn} obj Optional instance to populate.
     * @return {module:model/ResetLinkInfoReturn} The populated <code>ResetLinkInfoReturn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResetLinkInfoReturn();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResetLinkInfoReturn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResetLinkInfoReturn</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }

        return true;
    }


}



/**
 * The user identifier
 * @member {String} userId
 */
ResetLinkInfoReturn.prototype['userId'] = undefined;

/**
 * The user name
 * @member {String} username
 */
ResetLinkInfoReturn.prototype['username'] = undefined;

/**
 * The domain name
 * @member {String} domain
 */
ResetLinkInfoReturn.prototype['domain'] = undefined;






export default ResetLinkInfoReturn;

