/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SnapshotSharingPermissions model module.
 * @module model/SnapshotSharingPermissions
 * @version 0.4.1
 */
class SnapshotSharingPermissions {
    /**
     * Constructs a new <code>SnapshotSharingPermissions</code>.
     * 
     * @alias module:model/SnapshotSharingPermissions
     */
    constructor() { 
        
        SnapshotSharingPermissions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SnapshotSharingPermissions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SnapshotSharingPermissions} obj Optional instance to populate.
     * @return {module:model/SnapshotSharingPermissions} The populated <code>SnapshotSharingPermissions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SnapshotSharingPermissions();

            if (data.hasOwnProperty('cloudEnabled')) {
                obj['cloudEnabled'] = ApiClient.convertToType(data['cloudEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('domainEnabled')) {
                obj['domainEnabled'] = ApiClient.convertToType(data['domainEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('publicLink')) {
                obj['publicLink'] = ApiClient.convertToType(data['publicLink'], 'Boolean');
            }
            if (data.hasOwnProperty('domainRestrictedLink')) {
                obj['domainRestrictedLink'] = ApiClient.convertToType(data['domainRestrictedLink'], 'Boolean');
            }
            if (data.hasOwnProperty('passwordPublicLink')) {
                obj['passwordPublicLink'] = ApiClient.convertToType(data['passwordPublicLink'], 'Boolean');
            }
            if (data.hasOwnProperty('emailInvite')) {
                obj['emailInvite'] = ApiClient.convertToType(data['emailInvite'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SnapshotSharingPermissions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SnapshotSharingPermissions</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Indicates if snapshot permissions are enabled by the cloud admin
 * @member {Boolean} cloudEnabled
 */
SnapshotSharingPermissions.prototype['cloudEnabled'] = undefined;

/**
 * Indicates if snapshot permissions are enabled by the domain admin
 * @member {Boolean} domainEnabled
 */
SnapshotSharingPermissions.prototype['domainEnabled'] = undefined;

/**
 * Indicates if public link access is enabled
 * @member {Boolean} publicLink
 */
SnapshotSharingPermissions.prototype['publicLink'] = undefined;

/**
 * Indicates if domain-restricted link access is enabled
 * @member {Boolean} domainRestrictedLink
 */
SnapshotSharingPermissions.prototype['domainRestrictedLink'] = undefined;

/**
 * Indicates if password-protected public link access is enabled
 * @member {Boolean} passwordPublicLink
 */
SnapshotSharingPermissions.prototype['passwordPublicLink'] = undefined;

/**
 * Indicates if email invite access is enabled
 * @member {Boolean} emailInvite
 */
SnapshotSharingPermissions.prototype['emailInvite'] = undefined;






export default SnapshotSharingPermissions;

