/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SnapshotRequest model module.
 * @module model/SnapshotRequest
 * @version 0.4.3
 */
class SnapshotRequest {
    /**
     * Constructs a new <code>SnapshotRequest</code>.
     * 
     * @alias module:model/SnapshotRequest
     */
    constructor() { 
        
        SnapshotRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SnapshotRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SnapshotRequest} obj Optional instance to populate.
     * @return {module:model/SnapshotRequest} The populated <code>SnapshotRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SnapshotRequest();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('springboard')) {
                obj['springboard'] = ApiClient.convertToType(data['springboard'], 'Boolean');
            }
            if (data.hasOwnProperty('live')) {
                obj['live'] = ApiClient.convertToType(data['live'], 'Boolean');
            }
            if (data.hasOwnProperty('fresh')) {
                obj['fresh'] = ApiClient.convertToType(data['fresh'], 'Boolean');
            }
            if (data.hasOwnProperty('deviceName')) {
                obj['deviceName'] = ApiClient.convertToType(data['deviceName'], 'String');
            }
            if (data.hasOwnProperty('task')) {
                obj['task'] = ApiClient.convertToType(data['task'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('orderBy')) {
                obj['orderBy'] = ApiClient.convertToType(data['orderBy'], 'String');
            }
            if (data.hasOwnProperty('search')) {
                obj['search'] = ApiClient.convertToType(data['search'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SnapshotRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SnapshotRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['deviceName'] && !(typeof data['deviceName'] === 'string' || data['deviceName'] instanceof String)) {
            throw new Error("Expected the field `deviceName` to be a primitive type in the JSON string but got " + data['deviceName']);
        }
        // ensure the json data is a string
        if (data['task'] && !(typeof data['task'] === 'string' || data['task'] instanceof String)) {
            throw new Error("Expected the field `task` to be a primitive type in the JSON string but got " + data['task']);
        }
        // ensure the json data is a string
        if (data['to'] && !(typeof data['to'] === 'string' || data['to'] instanceof String)) {
            throw new Error("Expected the field `to` to be a primitive type in the JSON string but got " + data['to']);
        }
        // ensure the json data is a string
        if (data['from'] && !(typeof data['from'] === 'string' || data['from'] instanceof String)) {
            throw new Error("Expected the field `from` to be a primitive type in the JSON string but got " + data['from']);
        }
        // ensure the json data is a string
        if (data['orderBy'] && !(typeof data['orderBy'] === 'string' || data['orderBy'] instanceof String)) {
            throw new Error("Expected the field `orderBy` to be a primitive type in the JSON string but got " + data['orderBy']);
        }
        // ensure the json data is a string
        if (data['search'] && !(typeof data['search'] === 'string' || data['search'] instanceof String)) {
            throw new Error("Expected the field `search` to be a primitive type in the JSON string but got " + data['search']);
        }

        return true;
    }


}



/**
 * Number of entries to return, defaults to 100
 * @member {Number} limit
 */
SnapshotRequest.prototype['limit'] = undefined;

/**
 * Number of rows to skip, defaults to 0
 * @member {Number} offset
 */
SnapshotRequest.prototype['offset'] = undefined;

/**
 * Denotes whether snapshot was a springboard snapshot
 * @member {Boolean} springboard
 */
SnapshotRequest.prototype['springboard'] = undefined;

/**
 * Denotes whether snapshot was a live snapshot
 * @member {Boolean} live
 */
SnapshotRequest.prototype['live'] = undefined;

/**
 * Denotes whether snapshot was created immediately after the device was restored
 * @member {Boolean} fresh
 */
SnapshotRequest.prototype['fresh'] = undefined;

/**
 * Name of device
 * @member {String} deviceName
 */
SnapshotRequest.prototype['deviceName'] = undefined;

/**
 * Task being executed on snapshot
 * @member {String} task
 */
SnapshotRequest.prototype['task'] = undefined;

/**
 * Date to filter to, keyed off of createdAt
 * @member {String} to
 */
SnapshotRequest.prototype['to'] = undefined;

/**
 * Date to filter from, keyed off of createdAt
 * @member {String} from
 */
SnapshotRequest.prototype['from'] = undefined;

/**
 * Sorting order ('-createdAt' or 'createdAt'), defaults to -createdAt
 * @member {String} orderBy
 */
SnapshotRequest.prototype['orderBy'] = undefined;

/**
 * Last filter applied and searches on snapshot / associated instance name and snapshot / instance id
 * @member {String} search
 */
SnapshotRequest.prototype['search'] = undefined;






export default SnapshotRequest;

