/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClusterSnapshot from './ClusterSnapshot';

/**
 * The SnapshotList model module.
 * @module model/SnapshotList
 * @version 0.4.3
 */
class SnapshotList {
    /**
     * Constructs a new <code>SnapshotList</code>.
     * 
     * @alias module:model/SnapshotList
     */
    constructor() { 
        
        SnapshotList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SnapshotList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SnapshotList} obj Optional instance to populate.
     * @return {module:model/SnapshotList} The populated <code>SnapshotList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SnapshotList();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [ClusterSnapshot]);
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SnapshotList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SnapshotList</code>.
     */
    static validateJSON(data) {
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                ClusterSnapshot.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * List of snapshots
 * @member {Array.<module:model/ClusterSnapshot>} results
 */
SnapshotList.prototype['results'] = undefined;

/**
 * Offset for pagination, defaults to 0
 * @member {Number} offset
 */
SnapshotList.prototype['offset'] = undefined;

/**
 * Number of items to return, defaults to 100, minimum of 1 and maximum of 1000
 * @member {Number} limit
 */
SnapshotList.prototype['limit'] = undefined;

/**
 * Number of items in current response
 * @member {Number} count
 */
SnapshotList.prototype['count'] = undefined;






export default SnapshotList;

