/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 4.2.0-6a4b86f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TouchInput model module.
 * @module model/TouchInput
 * @version 0.2.0
 */
class TouchInput {
    /**
     * Constructs a new <code>TouchInput</code>.
     * 
     * @alias module:model/TouchInput
     */
    constructor() { 
        
        TouchInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TouchInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TouchInput} obj Optional instance to populate.
     * @return {module:model/TouchInput} The populated <code>TouchInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TouchInput();

            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TouchInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TouchInput</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Finger Positions
 * @member {Object} position
 */
TouchInput.prototype['position'] = undefined;






export default TouchInput;

