/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateTrialRequestParams model module.
 * @module model/UpdateTrialRequestParams
 * @version 0.4.3
 */
class UpdateTrialRequestParams {
    /**
     * Constructs a new <code>UpdateTrialRequestParams</code>.
     * 
     * @alias module:model/UpdateTrialRequestParams
     */
    constructor() { 
        
        UpdateTrialRequestParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateTrialRequestParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateTrialRequestParams} obj Optional instance to populate.
     * @return {module:model/UpdateTrialRequestParams} The populated <code>UpdateTrialRequestParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateTrialRequestParams();

            if (data.hasOwnProperty('extensionDays')) {
                obj['extensionDays'] = ApiClient.convertToType(data['extensionDays'], 'Number');
            }
            if (data.hasOwnProperty('extensionHours')) {
                obj['extensionHours'] = ApiClient.convertToType(data['extensionHours'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateTrialRequestParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateTrialRequestParams</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Days to add to the trial before it ends.
 * @member {Number} extensionDays
 */
UpdateTrialRequestParams.prototype['extensionDays'] = undefined;

/**
 * Hours of usage to add to the trial. This will be either device-hours or core-hours depending on the trial.
 * @member {Number} extensionHours
 */
UpdateTrialRequestParams.prototype['extensionHours'] = undefined;






export default UpdateTrialRequestParams;

