/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 4.5.0-16775
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1LoadExtensionParameters model module.
 * @module model/V1LoadExtensionParameters
 * @version 0.3.2
 */
class V1LoadExtensionParameters {
    /**
     * Constructs a new <code>V1LoadExtensionParameters</code>.
     * 
     * @alias module:model/V1LoadExtensionParameters
     * @param imageId {String} The uuid of the image to load
     */
    constructor(imageId) { 
        
        V1LoadExtensionParameters.initialize(this, imageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, imageId) { 
        obj['imageId'] = imageId;
    }

    /**
     * Constructs a <code>V1LoadExtensionParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1LoadExtensionParameters} obj Optional instance to populate.
     * @return {module:model/V1LoadExtensionParameters} The populated <code>V1LoadExtensionParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1LoadExtensionParameters();

            if (data.hasOwnProperty('imageId')) {
                obj['imageId'] = ApiClient.convertToType(data['imageId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1LoadExtensionParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1LoadExtensionParameters</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1LoadExtensionParameters.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['imageId'] && !(typeof data['imageId'] === 'string' || data['imageId'] instanceof String)) {
            throw new Error("Expected the field `imageId` to be a primitive type in the JSON string but got " + data['imageId']);
        }

        return true;
    }


}

V1LoadExtensionParameters.RequiredProperties = ["imageId"];

/**
 * The uuid of the image to load
 * @member {String} imageId
 */
V1LoadExtensionParameters.prototype['imageId'] = undefined;






export default V1LoadExtensionParameters;

