/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CorelliumClient);
  }
}(this, function(expect, CorelliumClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CorelliumClient.FirmwareAsset();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FirmwareAsset', function() {
    it('should create an instance of FirmwareAsset', function() {
      // uncomment below and update the code to test FirmwareAsset
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be.a(CorelliumClient.FirmwareAsset);
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property payload (base name: "payload")', function() {
      // uncomment below and update the code to test the property payload
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property md5sum (base name: "md5sum")', function() {
      // uncomment below and update the code to test the property md5sum
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property sha1sum (base name: "sha1sum")', function() {
      // uncomment below and update the code to test the property sha1sum
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property sha256sum (base name: "sha256sum")', function() {
      // uncomment below and update the code to test the property sha256sum
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property uploaddate (base name: "uploaddate")', function() {
      // uncomment below and update the code to test the property uploaddate
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CorelliumClient.FirmwareAsset();
      //expect(instance).to.be();
    });

  });

}));
