/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CorelliumClient);
  }
}(this, function(expect, CorelliumClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CorelliumClient.InstanceInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InstanceInput', function() {
    it('should create an instance of InstanceInput', function() {
      // uncomment below and update the code to test InstanceInput
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be.a(CorelliumClient.InstanceInput);
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property buttons (base name: "buttons")', function() {
      // uncomment below and update the code to test the property buttons
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property normalized (base name: "normalized")', function() {
      // uncomment below and update the code to test the property normalized
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property wait (base name: "wait")', function() {
      // uncomment below and update the code to test the property wait
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property start (base name: "start")', function() {
      // uncomment below and update the code to test the property start
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property end (base name: "end")', function() {
      // uncomment below and update the code to test the property end
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property bezierPoints (base name: "bezierPoints")', function() {
      // uncomment below and update the code to test the property bezierPoints
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property startButtons (base name: "startButtons")', function() {
      // uncomment below and update the code to test the property startButtons
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property endButtons (base name: "endButtons")', function() {
      // uncomment below and update the code to test the property endButtons
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property required (base name: "required")', function() {
      // uncomment below and update the code to test the property required
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

    it('should have the property keyDuration (base name: "keyDuration")', function() {
      // uncomment below and update the code to test the property keyDuration
      //var instance = new CorelliumClient.InstanceInput();
      //expect(instance).to.be();
    });

  });

}));
