/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CorelliumClient);
  }
}(this, function(expect, CorelliumClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CorelliumClient.MeteredSubscriptionUsage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MeteredSubscriptionUsage', function() {
    it('should create an instance of MeteredSubscriptionUsage', function() {
      // uncomment below and update the code to test MeteredSubscriptionUsage
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be.a(CorelliumClient.MeteredSubscriptionUsage);
    });

    it('should have the property burstRate (base name: "burst_rate")', function() {
      // uncomment below and update the code to test the property burstRate
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property allocatedHours (base name: "allocated_hours")', function() {
      // uncomment below and update the code to test the property allocatedHours
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property planBilledAmount (base name: "plan_billed_amount")', function() {
      // uncomment below and update the code to test the property planBilledAmount
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property planBilledUnits (base name: "plan_billed_units")', function() {
      // uncomment below and update the code to test the property planBilledUnits
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property burstBilledAmount (base name: "burst_billed_amount")', function() {
      // uncomment below and update the code to test the property burstBilledAmount
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property burstBilledUnits (base name: "burst_billed_units")', function() {
      // uncomment below and update the code to test the property burstBilledUnits
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property burstOutstandingAmount (base name: "burst_outstanding_amount")', function() {
      // uncomment below and update the code to test the property burstOutstandingAmount
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property burstOutstandingUnits (base name: "burst_outstanding_units")', function() {
      // uncomment below and update the code to test the property burstOutstandingUnits
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property totalUsageAmount (base name: "total_usage_amount")', function() {
      // uncomment below and update the code to test the property totalUsageAmount
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

    it('should have the property totalUsedUnits (base name: "total_used_units")', function() {
      // uncomment below and update the code to test the property totalUsedUnits
      //var instance = new CorelliumClient.MeteredSubscriptionUsage();
      //expect(instance).to.be();
    });

  });

}));
