/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 7.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CorelliumClient);
  }
}(this, function(expect, CorelliumClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CorelliumClient.SharedSnapshotsInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SharedSnapshotsInfo', function() {
    it('should create an instance of SharedSnapshotsInfo', function() {
      // uncomment below and update the code to test SharedSnapshotsInfo
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be.a(CorelliumClient.SharedSnapshotsInfo);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be();
    });

    it('should have the property sharedOn (base name: "sharedOn")', function() {
      // uncomment below and update the code to test the property sharedOn
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be();
    });

    it('should have the property sharedWithMember (base name: "sharedWithMember")', function() {
      // uncomment below and update the code to test the property sharedWithMember
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be();
    });

    it('should have the property sharedBy (base name: "sharedBy")', function() {
      // uncomment below and update the code to test the property sharedBy
      //var instance = new CorelliumClient.SharedSnapshotsInfo();
      //expect(instance).to.be();
    });

  });

}));
